version: "3"
services:
  # APP
  booking:
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:15432/bookingdb?currentSchema=booking&stringtype=unspecified&ApplicationName=booking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_FLYWAY_SCHEMAS=booking
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - booking_network
  # PostgreSQL
  db:
    container_name: challenge_bookingdb
    image: postgres:12.3-alpine
    #volumes:
    #  - booking_db:/var/lib/postgresql/data
    expose:
      - 15432
    ports:
      - 15432:15432
    command:
      -p 15432
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - booking_network
volumes:
  booking_db:
networks:
  booking_network:
    driver: bridge