CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE IF NOT EXISTS TRAIL
(
    ID          UUID        NOT NULL,
    NAME        TEXT UNIQUE NOT NULL,
    START_AT    TIME        NOT NULL,
    END_AT      TIME        NOT NULL,
    MINIMUM_AGE NUMERIC     NOT NULL,
    MAXIMUM_AGE NUMERIC     NOT NULL,
    UNIT_PRICE  NUMERIC     NOT NULL,

    PRIMARY KEY (ID),

    CHECK (END_AT > START_AT),
    CHECK (MINIMUM_AGE > 0),
    CHECK (MAXIMUM_AGE > MINIMUM_AGE)
);

CREATE TABLE IF NOT EXISTS HIKER
(
    ID            UUID NOT NULL,
    NAME          TEXT NOT NULL,
    SURNAME       TEXT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE_NUMBER  TEXT NOT NULL,
    EMAIL         TEXT,

    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_HIKER UNIQUE (NAME, SURNAME, DATE_OF_BIRTH),

    CHECK (DATE_OF_BIRTH < NOW())
);

CREATE TABLE IF NOT EXISTS BOOKING
(
    ID           UUID    NOT NULL,
    TRAIL_ID     UUID    NOT NULL,
    DATE         DATE    NOT NULL,
    IS_CANCELLED BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (ID),
    CONSTRAINT FK_TRAIL FOREIGN KEY (TRAIL_ID) REFERENCES TRAIL (ID),

    CHECK (DATE >= NOW())
);

CREATE TABLE IF NOT EXISTS BOOKING_HIKER
(
    ID         UUID NOT NULL DEFAULT UUID_GENERATE_V4(),
    BOOKING_ID UUID NOT NULL,
    HIKER_ID   UUID NOT NULL,

    PRIMARY KEY (ID),
    CONSTRAINT FK_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING (ID),
    CONSTRAINT FK_HIKER FOREIGN KEY (HIKER_ID) REFERENCES HIKER (ID)
);
